import logging
import os

import httpx
from lsprotocol.types import (
    TEXT_DOCUMENT_COMPLETION,
    CompletionItem,
    CompletionItemKind,
    CompletionList,
    CompletionParams,
)
from pygls.server import LanguageServer

logger = logging.getLogger(__name__)

BACKEND_URL = os.getenv("BACKEND_URL", "http://localhost:8000")

server = LanguageServer("ai-dev-assistant", "v0.1.0")

# Reused across completion requests (called frequently); the process is
# short-lived so the client is closed on shutdown if pygls exposes a hook.
_http_client = httpx.AsyncClient(timeout=15.0)


def _get_document_text(ls: LanguageServer, uri: str) -> str:
    doc = ls.workspace.get_document(uri)
    return doc.source if doc else ""


@server.feature(TEXT_DOCUMENT_COMPLETION)
async def completions(ls: LanguageServer, params: CompletionParams) -> CompletionList:
    uri = params.text_document.uri
    text = _get_document_text(ls, uri)

    language = "python" if uri.endswith(".py") else "unknown"

    try:
        resp = await _http_client.post(
            f"{BACKEND_URL}/completion/",
            json={"code": text, "language": language, "cursor_line": params.position.line},
        )
        resp.raise_for_status()
        suggestion = resp.json()["suggestion"]
    except (httpx.HTTPError, httpx.TimeoutException) as exc:
        logger.warning("Backend completion request failed: %s", exc)
        return CompletionList(is_incomplete=False, items=[])
    except Exception:
        logger.exception("Unexpected error while handling completion")
        return CompletionList(is_incomplete=False, items=[])

    item = CompletionItem(
        label="AI suggestion",
        kind=CompletionItemKind.Text,
        insert_text=suggestion,
        documentation="Generated by AI Dev Assistant",
    )
    return CompletionList(is_incomplete=False, items=[item])


if __name__ == "__main__":
    import asyncio

    host = os.getenv("LSP_HOST", "0.0.0.0")  # nosec B104 — container must bind all interfaces
    port = int(os.getenv("LSP_PORT", "2087"))
    try:
        server.start_tcp(host, port)
    finally:
        asyncio.run(_http_client.aclose())
