import os
import httpx
from pygls.server import LanguageServer
from lsprotocol.types import (
    TEXT_DOCUMENT_COMPLETION,
    CompletionItem,
    CompletionItemKind,
    CompletionList,
    CompletionParams,
)

BACKEND_URL = os.getenv("BACKEND_URL", "http://backend:8000")

server = LanguageServer("ai-dev-assistant", "v0.1.0")


def _get_document_text(ls: LanguageServer, uri: str) -> str:
    doc = ls.workspace.get_document(uri)
    return doc.source if doc else ""


@server.feature(TEXT_DOCUMENT_COMPLETION)
async def completions(ls: LanguageServer, params: CompletionParams) -> CompletionList:
    uri = params.text_document.uri
    text = _get_document_text(ls, uri)

    language = "python" if uri.endswith(".py") else "unknown"

    try:
        async with httpx.AsyncClient(timeout=15.0) as client:
            resp = await client.post(
                f"{BACKEND_URL}/completion/",
                json={"code": text, "language": language, "cursor_line": params.position.line},
            )
            resp.raise_for_status()
            suggestion = resp.json()["suggestion"]
    except Exception:
        return CompletionList(is_incomplete=False, items=[])

    item = CompletionItem(
        label="AI suggestion",
        kind=CompletionItemKind.Text,
        insert_text=suggestion,
        documentation="Generated by Gemini",
    )
    return CompletionList(is_incomplete=False, items=[item])


if __name__ == "__main__":
    host = os.getenv("LSP_HOST", "0.0.0.0")
    port = int(os.getenv("LSP_PORT", "2087"))
    server.start_tcp(host, port)
